// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CliftonQuartetHomepageDocumentDataSlicesSlice =
  | ImagesSectionSlice
  | TestimonialsSlice
  | WeddingsSlice
  | RepertoireSlice
  | AnimatedInstrumentsSlice
  | HeroSlice;

/**
 * Content for Clifton Quartet Homepage documents
 */
interface CliftonQuartetHomepageDocumentData {
  /**
   * Slice Zone field in *Clifton Quartet Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: clifton_quartet_homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CliftonQuartetHomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Clifton Quartet Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: clifton_quartet_homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Clifton Quartet Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: clifton_quartet_homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Clifton Quartet Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clifton_quartet_homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Clifton Quartet Homepage document from Prismic
 *
 * - **API ID**: `clifton_quartet_homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CliftonQuartetHomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CliftonQuartetHomepageDocumentData>,
    "clifton_quartet_homepage",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Navigation link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].navigation_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Contact us text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_us_text: prismic.KeyTextField;

  /**
   * Phone number field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  phone_number: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Email field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Footer copyrights field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_copyrights
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_copyrights: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Item in *String Quartet Repertoire → Classical*
 */
export interface StringQuartetRepertoireDocumentDataClassicalItem {
  /**
   * Composer field in *String Quartet Repertoire → Classical*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.classical[].composer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  composer: prismic.KeyTextField;

  /**
   * Song Title field in *String Quartet Repertoire → Classical*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.classical[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Item in *String Quartet Repertoire → Popular*
 */
export interface StringQuartetRepertoireDocumentDataPopularItem {
  /**
   * Song Title field in *String Quartet Repertoire → Popular*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.popular[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Item in *String Quartet Repertoire → Beatles*
 */
export interface StringQuartetRepertoireDocumentDataBeatlesItem {
  /**
   * Song Title field in *String Quartet Repertoire → Beatles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.beatles[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Item in *String Quartet Repertoire → Rags*
 */
export interface StringQuartetRepertoireDocumentDataRagsItem {
  /**
   * Song Title field in *String Quartet Repertoire → Rags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.rags[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Item in *String Quartet Repertoire → Jazz Classics*
 */
export interface StringQuartetRepertoireDocumentDataJazzClassicsItem {
  /**
   * Song Title field in *String Quartet Repertoire → Jazz Classics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.jazz_classics[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Item in *String Quartet Repertoire → Film and Show*
 */
export interface StringQuartetRepertoireDocumentDataFilmAndShowItem {
  /**
   * Song Title field in *String Quartet Repertoire → Film and Show*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.film_and_show[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Item in *String Quartet Repertoire → Rock and Pop*
 */
export interface StringQuartetRepertoireDocumentDataRockAndPopItem {
  /**
   * Composer field in *String Quartet Repertoire → Rock and Pop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.rock_and_pop[].composer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  composer: prismic.KeyTextField;

  /**
   * Song Title field in *String Quartet Repertoire → Rock and Pop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.rock_and_pop[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Content for String Quartet Repertoire documents
 */
interface StringQuartetRepertoireDocumentData {
  /**
   * Classical field in *String Quartet Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.classical[]
   * - **Tab**: Classical
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  classical: prismic.GroupField<
    Simplify<StringQuartetRepertoireDocumentDataClassicalItem>
  > /**
   * Popular field in *String Quartet Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.popular[]
   * - **Tab**: Popular
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  popular: prismic.GroupField<
    Simplify<StringQuartetRepertoireDocumentDataPopularItem>
  > /**
   * Beatles field in *String Quartet Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.beatles[]
   * - **Tab**: Beatles
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  beatles: prismic.GroupField<
    Simplify<StringQuartetRepertoireDocumentDataBeatlesItem>
  > /**
   * Rags field in *String Quartet Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.rags[]
   * - **Tab**: Rags
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  rags: prismic.GroupField<
    Simplify<StringQuartetRepertoireDocumentDataRagsItem>
  > /**
   * Jazz Classics field in *String Quartet Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.jazz_classics[]
   * - **Tab**: Jazz Classics
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  jazz_classics: prismic.GroupField<
    Simplify<StringQuartetRepertoireDocumentDataJazzClassicsItem>
  > /**
   * Film and Show field in *String Quartet Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.film_and_show[]
   * - **Tab**: Film and Show
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  film_and_show: prismic.GroupField<
    Simplify<StringQuartetRepertoireDocumentDataFilmAndShowItem>
  > /**
   * Rock and Pop field in *String Quartet Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_quartet_repertoire.rock_and_pop[]
   * - **Tab**: Rock and Pop
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  rock_and_pop: prismic.GroupField<
    Simplify<StringQuartetRepertoireDocumentDataRockAndPopItem>
  >;
}

/**
 * String Quartet Repertoire document from Prismic
 *
 * - **API ID**: `string_quartet_repertoire`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StringQuartetRepertoireDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StringQuartetRepertoireDocumentData>,
    "string_quartet_repertoire",
    Lang
  >;

/**
 * Item in *String Trio Repertoire → Classical*
 */
export interface StringTrioRepertoireDocumentDataClassicalItem {
  /**
   * Composer field in *String Trio Repertoire → Classical*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.classical[].composer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  composer: prismic.KeyTextField;

  /**
   * Song Title field in *String Trio Repertoire → Classical*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.classical[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Item in *String Trio Repertoire → Popular Songs*
 */
export interface StringTrioRepertoireDocumentDataPopularSongsItem {
  /**
   * Composer field in *String Trio Repertoire → Popular Songs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.popular_songs[].composer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  composer: prismic.KeyTextField;

  /**
   * Song Title field in *String Trio Repertoire → Popular Songs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.popular_songs[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Item in *String Trio Repertoire → Lighter Repertoire*
 */
export interface StringTrioRepertoireDocumentDataLighterRepertoireItem {
  /**
   * Composer field in *String Trio Repertoire → Lighter Repertoire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.lighter_repertoire[].composer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  composer: prismic.KeyTextField;

  /**
   * Song Title field in *String Trio Repertoire → Lighter Repertoire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.lighter_repertoire[].song_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_title: prismic.KeyTextField;
}

/**
 * Content for String Trio Repertoire documents
 */
interface StringTrioRepertoireDocumentData {
  /**
   * Classical field in *String Trio Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.classical[]
   * - **Tab**: Classical
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  classical: prismic.GroupField<
    Simplify<StringTrioRepertoireDocumentDataClassicalItem>
  > /**
   * Popular Songs field in *String Trio Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.popular_songs[]
   * - **Tab**: Popular Songs
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  popular_songs: prismic.GroupField<
    Simplify<StringTrioRepertoireDocumentDataPopularSongsItem>
  > /**
   * Lighter Repertoire field in *String Trio Repertoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: string_trio_repertoire.lighter_repertoire[]
   * - **Tab**: Lighter Repertoire
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  lighter_repertoire: prismic.GroupField<
    Simplify<StringTrioRepertoireDocumentDataLighterRepertoireItem>
  >;
}

/**
 * String Trio Repertoire document from Prismic
 *
 * - **API ID**: `string_trio_repertoire`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StringTrioRepertoireDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StringTrioRepertoireDocumentData>,
    "string_trio_repertoire",
    Lang
  >;

type ThePlayersDocumentDataSlicesSlice =
  | ImagesSectionSlice
  | PlayersBioSlice
  | TestimonialsSlice
  | WeddingsSlice
  | HeroSlice;

/**
 * Content for The Players documents
 */
interface ThePlayersDocumentData {
  /**
   * Slice Zone field in *The Players*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: the_players.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ThePlayersDocumentDataSlicesSlice> /**
   * Meta Title field in *The Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: the_players.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: the_players.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Players*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_players.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Players document from Prismic
 *
 * - **API ID**: `the_players`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThePlayersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ThePlayersDocumentData>,
    "the_players",
    Lang
  >;

type TheRepertoireDocumentDataSlicesSlice =
  | ImagesSectionSlice
  | RepertoireSlice
  | TestimonialsSlice
  | WeddingsSlice
  | TheRepertoireSlice
  | HeroSlice;

/**
 * Content for The Repertoire documents
 */
interface TheRepertoireDocumentData {
  /**
   * Slice Zone field in *The Repertoire*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: the_repertoire.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TheRepertoireDocumentDataSlicesSlice> /**
   * Meta Title field in *The Repertoire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: the_repertoire.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Repertoire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: the_repertoire.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Repertoire*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_repertoire.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Repertoire document from Prismic
 *
 * - **API ID**: `the_repertoire`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheRepertoireDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheRepertoireDocumentData>,
    "the_repertoire",
    Lang
  >;

type WeddingsAndEventsDocumentDataSlicesSlice =
  | ImagesSectionSlice
  | TestimonialsSlice
  | WeddingsSlice
  | HeroSlice;

/**
 * Content for Weddings & Events documents
 */
interface WeddingsAndEventsDocumentData {
  /**
   * Slice Zone field in *Weddings & Events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings_and_events.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WeddingsAndEventsDocumentDataSlicesSlice> /**
   * Meta Title field in *Weddings & Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: weddings_and_events.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Weddings & Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: weddings_and_events.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Weddings & Events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings_and_events.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Weddings & Events document from Prismic
 *
 * - **API ID**: `weddings_and_events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WeddingsAndEventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WeddingsAndEventsDocumentData>,
    "weddings_and_events",
    Lang
  >;

export type AllDocumentTypes =
  | CliftonQuartetHomepageDocument
  | SettingsDocument
  | StringQuartetRepertoireDocument
  | StringTrioRepertoireDocument
  | ThePlayersDocument
  | TheRepertoireDocument
  | WeddingsAndEventsDocument;

/**
 * Primary content in *AnimatedInstruments → Default → Primary*
 */
export interface AnimatedInstrumentsSliceDefaultPrimary {
  /**
   * Background Image field in *AnimatedInstruments → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_instruments.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for AnimatedInstruments Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnimatedInstrumentsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnimatedInstrumentsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AnimatedInstruments*
 */
type AnimatedInstrumentsSliceVariation = AnimatedInstrumentsSliceDefault;

/**
 * AnimatedInstruments Shared Slice
 *
 * - **API ID**: `animated_instruments`
 * - **Description**: AnimatedInstruments
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnimatedInstrumentsSlice = prismic.SharedSlice<
  "animated_instruments",
  AnimatedInstrumentsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Clifton String Quartet
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImagesSection → Default → Primary*
 */
export interface ImagesSectionSliceDefaultPrimary {
  /**
   * Image 1 field in *ImagesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: images_section.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *ImagesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: images_section.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *ImagesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: images_section.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;
}

/**
 * Default variation for ImagesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImagesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImagesSection*
 */
type ImagesSectionSliceVariation = ImagesSectionSliceDefault;

/**
 * ImagesSection Shared Slice
 *
 * - **API ID**: `images_section`
 * - **Description**: ImagesSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSectionSlice = prismic.SharedSlice<
  "images_section",
  ImagesSectionSliceVariation
>;

/**
 * Item in *PlayersBio → Default → Primary → Player bio*
 */
export interface PlayersBioSliceDefaultPrimaryPlayerBioItem {
  /**
   * Player photo field in *PlayersBio → Default → Primary → Player bio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: players_bio.default.primary.player_bio[].player_photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  player_photo: prismic.ImageField<never>;

  /**
   * Player name field in *PlayersBio → Default → Primary → Player bio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: players_bio.default.primary.player_bio[].player_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  player_name: prismic.RichTextField;

  /**
   * Player bio field in *PlayersBio → Default → Primary → Player bio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: players_bio.default.primary.player_bio[].player_bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  player_bio: prismic.RichTextField;
}

/**
 * Primary content in *PlayersBio → Default → Primary*
 */
export interface PlayersBioSliceDefaultPrimary {
  /**
   * Title field in *PlayersBio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: players_bio.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub heading field in *PlayersBio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: players_bio.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Background Image field in *PlayersBio → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: players_bio.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Color field in *PlayersBio → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: players_bio.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Player bio field in *PlayersBio → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: players_bio.default.primary.player_bio[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  player_bio: prismic.GroupField<
    Simplify<PlayersBioSliceDefaultPrimaryPlayerBioItem>
  >;
}

/**
 * Default variation for PlayersBio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlayersBioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PlayersBioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PlayersBio*
 */
type PlayersBioSliceVariation = PlayersBioSliceDefault;

/**
 * PlayersBio Shared Slice
 *
 * - **API ID**: `players_bio`
 * - **Description**: PlayersBio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlayersBioSlice = prismic.SharedSlice<
  "players_bio",
  PlayersBioSliceVariation
>;

/**
 * Item in *VinylPlayer → Default → Primary → Repertoire Carousel*
 */
export interface RepertoireSliceDefaultPrimaryRepertoireCarouselItem {
  /**
   * Artist field in *VinylPlayer → Default → Primary → Repertoire Carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.repertoire_carousel[].artist
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist: prismic.KeyTextField;

  /**
   * Song field in *VinylPlayer → Default → Primary → Repertoire Carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.repertoire_carousel[].song
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song: prismic.KeyTextField;

  /**
   * MP3 File field in *VinylPlayer → Default → Primary → Repertoire Carousel*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.repertoire_carousel[].mp3_file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mp3_file: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *VinylPlayer → Default → Primary*
 */
export interface RepertoireSliceDefaultPrimary {
  /**
   * Background Image field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Color field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Title field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Vinyl Cover field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.vinyl_cover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  vinyl_cover: prismic.ImageField<never>;

  /**
   * Vinyl Back field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.vinyl_back
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  vinyl_back: prismic.ImageField<never>;

  /**
   * Repertoire Carousel field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.repertoire_carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repertoire_carousel: prismic.GroupField<
    Simplify<RepertoireSliceDefaultPrimaryRepertoireCarouselItem>
  >;

  /**
   * Aside image 1 desktop only field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.aside_image_1_desktop_only
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  aside_image_1_desktop_only: prismic.ImageField<never>;

  /**
   * Aside image 2 desktop only field in *VinylPlayer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.aside_image_2_desktop_only
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  aside_image_2_desktop_only: prismic.ImageField<never>;
}

/**
 * Default variation for VinylPlayer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RepertoireSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RepertoireSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VinylPlayer*
 */
type RepertoireSliceVariation = RepertoireSliceDefault;

/**
 * VinylPlayer Shared Slice
 *
 * - **API ID**: `repertoire`
 * - **Description**: Repertoire
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RepertoireSlice = prismic.SharedSlice<
  "repertoire",
  RepertoireSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonial*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialItem {
  /**
   * Testimonial message field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_message
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial_message: prismic.RichTextField;

  /**
   * Author field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Background Image field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Color field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Testimonial field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *TheRepertoire → Default → Primary*
 */
export interface TheRepertoireSliceDefaultPrimary {
  /**
   * Title field in *TheRepertoire → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_repertoire.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *TheRepertoire → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_repertoire.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Phone Number field in *TheRepertoire → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: the_repertoire.default.primary.phone_number
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  phone_number: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Email field in *TheRepertoire → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: the_repertoire.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for TheRepertoire Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TheRepertoireSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TheRepertoireSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TheRepertoire*
 */
type TheRepertoireSliceVariation = TheRepertoireSliceDefault;

/**
 * TheRepertoire Shared Slice
 *
 * - **API ID**: `the_repertoire`
 * - **Description**: TheRepertoire
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TheRepertoireSlice = prismic.SharedSlice<
  "the_repertoire",
  TheRepertoireSliceVariation
>;

/**
 * Primary content in *AboutUs → Default → Primary*
 */
export interface WeddingsSliceDefaultPrimary {
  /**
   * Title field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph 1 field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.paragraph_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_1: prismic.RichTextField;

  /**
   * Paragraph 2 field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.paragraph_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_2: prismic.RichTextField;

  /**
   * Paragraph 3 field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.paragraph_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_3: prismic.RichTextField;

  /**
   * Paragraph 4 field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.paragraph_4
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_4: prismic.RichTextField;

  /**
   * Paragraph 5 field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.paragraph_5
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_5: prismic.RichTextField;

  /**
   * Paragraph 6 field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.paragraph_6
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_6: prismic.RichTextField;

  /**
   * Paragraph 7 field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.paragraph_7
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_7: prismic.RichTextField;

  /**
   * Paragraph 8 field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weddings.default.primary.paragraph_8
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_8: prismic.RichTextField;

  /**
   * Right empty section color field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: yellow-100
   * - **API ID Path**: weddings.default.primary.right_empty_section_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  right_empty_section_color: prismic.KeyTextField;

  /**
   * Left empty section color field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: yellow-900
   * - **API ID Path**: weddings.default.primary.left_empty_section_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  left_empty_section_color: prismic.KeyTextField;

  /**
   * Background Color field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: white
   * - **API ID Path**: weddings.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_color: prismic.KeyTextField;
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WeddingsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WeddingsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUs*
 */
type WeddingsSliceVariation = WeddingsSliceDefault;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `weddings`
 * - **Description**: Weddings
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WeddingsSlice = prismic.SharedSlice<
  "weddings",
  WeddingsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CliftonQuartetHomepageDocument,
      CliftonQuartetHomepageDocumentData,
      CliftonQuartetHomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      StringQuartetRepertoireDocument,
      StringQuartetRepertoireDocumentData,
      StringQuartetRepertoireDocumentDataClassicalItem,
      StringQuartetRepertoireDocumentDataPopularItem,
      StringQuartetRepertoireDocumentDataBeatlesItem,
      StringQuartetRepertoireDocumentDataRagsItem,
      StringQuartetRepertoireDocumentDataJazzClassicsItem,
      StringQuartetRepertoireDocumentDataFilmAndShowItem,
      StringQuartetRepertoireDocumentDataRockAndPopItem,
      StringTrioRepertoireDocument,
      StringTrioRepertoireDocumentData,
      StringTrioRepertoireDocumentDataClassicalItem,
      StringTrioRepertoireDocumentDataPopularSongsItem,
      StringTrioRepertoireDocumentDataLighterRepertoireItem,
      ThePlayersDocument,
      ThePlayersDocumentData,
      ThePlayersDocumentDataSlicesSlice,
      TheRepertoireDocument,
      TheRepertoireDocumentData,
      TheRepertoireDocumentDataSlicesSlice,
      WeddingsAndEventsDocument,
      WeddingsAndEventsDocumentData,
      WeddingsAndEventsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AnimatedInstrumentsSlice,
      AnimatedInstrumentsSliceDefaultPrimary,
      AnimatedInstrumentsSliceVariation,
      AnimatedInstrumentsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImagesSectionSlice,
      ImagesSectionSliceDefaultPrimary,
      ImagesSectionSliceVariation,
      ImagesSectionSliceDefault,
      PlayersBioSlice,
      PlayersBioSliceDefaultPrimaryPlayerBioItem,
      PlayersBioSliceDefaultPrimary,
      PlayersBioSliceVariation,
      PlayersBioSliceDefault,
      RepertoireSlice,
      RepertoireSliceDefaultPrimaryRepertoireCarouselItem,
      RepertoireSliceDefaultPrimary,
      RepertoireSliceVariation,
      RepertoireSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TheRepertoireSlice,
      TheRepertoireSliceDefaultPrimary,
      TheRepertoireSliceVariation,
      TheRepertoireSliceDefault,
      WeddingsSlice,
      WeddingsSliceDefaultPrimary,
      WeddingsSliceVariation,
      WeddingsSliceDefault,
    };
  }
}
