// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CliftonQuartetHomepageDocumentDataSlicesSlice =
  | RepertoireSlice
  | AnimatedInstrumentsSlice
  | HeroSlice;

/**
 * Content for Clifton Quartet Homepage documents
 */
interface CliftonQuartetHomepageDocumentData {
  /**
   * Slice Zone field in *Clifton Quartet Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: clifton_quartet_homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CliftonQuartetHomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Clifton Quartet Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: clifton_quartet_homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Clifton Quartet Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: clifton_quartet_homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Clifton Quartet Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clifton_quartet_homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Clifton Quartet Homepage document from Prismic
 *
 * - **API ID**: `clifton_quartet_homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CliftonQuartetHomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CliftonQuartetHomepageDocumentData>,
    "clifton_quartet_homepage",
    Lang
  >;

export type AllDocumentTypes = CliftonQuartetHomepageDocument;

/**
 * Primary content in *AnimatedInstruments → Default → Primary*
 */
export interface AnimatedInstrumentsSliceDefaultPrimary {
  /**
   * Background Image field in *AnimatedInstruments → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_instruments.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for AnimatedInstruments Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnimatedInstrumentsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnimatedInstrumentsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AnimatedInstruments*
 */
type AnimatedInstrumentsSliceVariation = AnimatedInstrumentsSliceDefault;

/**
 * AnimatedInstruments Shared Slice
 *
 * - **API ID**: `animated_instruments`
 * - **Description**: AnimatedInstruments
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnimatedInstrumentsSlice = prismic.SharedSlice<
  "animated_instruments",
  AnimatedInstrumentsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Clifton String Quartet
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Repertoire → Default → Primary → Repertoire Carousel*
 */
export interface RepertoireSliceDefaultPrimaryRepertoireCarouselItem {
  /**
   * Artist field in *Repertoire → Default → Primary → Repertoire Carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.repertoire_carousel[].artist
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist: prismic.KeyTextField;

  /**
   * Song field in *Repertoire → Default → Primary → Repertoire Carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.repertoire_carousel[].song
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song: prismic.KeyTextField;
}

/**
 * Item in *Repertoire → Default → Primary → mp3 songs*
 */
export interface RepertoireSliceDefaultPrimaryMp3SongsItem {
  /**
   * Song field in *Repertoire → Default → Primary → mp3 songs*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: mp3 audio file
   * - **API ID Path**: repertoire.default.primary.mp3_songs[].song
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  song: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *Repertoire → Default → Primary*
 */
export interface RepertoireSliceDefaultPrimary {
  /**
   * Background Image field in *Repertoire → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Title field in *Repertoire → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Repertoire → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Repertoire Carousel field in *Repertoire → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.repertoire_carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repertoire_carousel: prismic.GroupField<
    Simplify<RepertoireSliceDefaultPrimaryRepertoireCarouselItem>
  >;

  /**
   * mp3 songs field in *Repertoire → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire.default.primary.mp3_songs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  mp3_songs: prismic.GroupField<
    Simplify<RepertoireSliceDefaultPrimaryMp3SongsItem>
  >;
}

/**
 * Default variation for Repertoire Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RepertoireSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RepertoireSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Repertoire*
 */
type RepertoireSliceVariation = RepertoireSliceDefault;

/**
 * Repertoire Shared Slice
 *
 * - **API ID**: `repertoire`
 * - **Description**: Repertoire
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RepertoireSlice = prismic.SharedSlice<
  "repertoire",
  RepertoireSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CliftonQuartetHomepageDocument,
      CliftonQuartetHomepageDocumentData,
      CliftonQuartetHomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AnimatedInstrumentsSlice,
      AnimatedInstrumentsSliceDefaultPrimary,
      AnimatedInstrumentsSliceVariation,
      AnimatedInstrumentsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      RepertoireSlice,
      RepertoireSliceDefaultPrimaryRepertoireCarouselItem,
      RepertoireSliceDefaultPrimaryMp3SongsItem,
      RepertoireSliceDefaultPrimary,
      RepertoireSliceVariation,
      RepertoireSliceDefault,
    };
  }
}
