// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  animated_instruments: dynamic(() => import("./AnimatedInstruments")),
  hero: dynamic(() => import("./Hero")),
  repertoire: dynamic(() => import("./VinylPlayer")),
  testimonials: dynamic(() => import("./Testimonials")),
  the_repertoire: dynamic(() => import("./TheRepertoire")),
  weddings: dynamic(() => import("./AboutUs")),
};
